version: '3.9'
services: 
  db: 
    image: mysql/mysql-server:latest
    container_name: gil-mysql
    environment: 
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=secret
    ports: 
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local